# Generated by Django 3.2 on 2021-04-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
