# Generated by Django 3.2 on 2021-04-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_my_user_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='user_cart',
        ),
    ]
