# Generated by Django 3.2 on 2021-04-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='is_admin',
        ),
    ]
