# Generated by Django 3.2 on 2021-04-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210414_0719'),
        ('products', '0003_auto_20210414_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.my_user')),
            ],
        ),
    ]
