# Generated by Django 3.2 on 2021-04-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210414_0719'),
        ('products', '0004_my_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_cart',
            new_name='Cart',
        ),
    ]
