# Generated by Django 3.2 on 2021-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_my_cart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='food',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.IntegerField(),
        ),
    ]
